services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clinic-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=ClinicDb;Username=postgres;Password=clinicpassword
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: clinic-postgres
    environment:
      POSTGRES_DB: ClinicDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: clinicpassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: